### ISSUE TITLE
Key Binding clash with PHP Code Sniffer package

### ISSUE THREAD

**Issue by aranw** [jonfinerty/sublime-snake#11]
The default key binding classes with PHP Code Sniffer package, I tried to change the keybinding but theres no Package Settings to alter these.

**Comment by aranw** [comment]
I ended up changing PHP Code Sniffer but having option to change Snake's Keybinding in Package Settings would be useful.

**Comment by jonfinerty** [comment]
I will be looking into on_query_context key event handlers so that the arrow keys are only overridden when a snake game is underway. Also configurable key bindings will be coming soon as well. Thanks.

**Comment by jonfinerty** [comment]
Alongside context-based key bindings, I've also added menu items to the package settings to the beta branch.
