### ISSUE TITLE
Do not override "move" commands and instead implement a context

### ISSUE THREAD

**Issue by FichteFoll** [jonfinerty/sublime-snake#12]
Instead of overriding default "up", "down", "left" and "right" keys you can define a context for the bindings that only triggers when the "game" is running.
There are several ways but the easiest would be to use an event listener, implement `on_query_context()` and use the defining key in the key bindings.

[Docs](https://www.sublimetext.com/docs/2/api_reference.html#sublime_plugin.EventListener)

**Comment by jonfinerty** [comment]
Thanks, I'll have a look at the on_query_context() stuff.

**Comment by jonfinerty** [comment]
This is now implemented on the beta branch and will be merged/released in the next week or so.
