### ISSUE TITLE
Strange behavior when repeating play

### ISSUE THREAD

**Issue by sc8696** [jonfinerty/sublime-snake#2]
![NvjBK](https://f.cloud.github.com/assets/1330098/62872/e129e4ca-5d8b-11e2-9661-a095a37bbace.png)

Play a game, lose, then play again and there's ... an extra playing field
Do it again, then there's another one etc.

**Comment by jonfinerty** [comment]
Now adds a new line to end of template file so that border always appears on a newline. Also means you now cannot die instantly if you try to spawn on the last line.
