### ISSUE TITLE
If you press up/down then left/right quickly enough after each other, the snake goes inside itself and dies

### ISSUE THREAD

**Issue by sc8696** [jonfinerty/sublime-snake#6]
![screenshot](https://f.cloud.github.com/assets/1330098/63074/f78f79a6-5db2-11e2-85fc-434b0c2af2c7.png)

Kinda hard to replicate... just gotta do it super fast...

**Comment by jonfinerty** [comment]
True bug. Fixed. Added direction intention which only updates direction once a game cycle.
